### ISSUE TITLE
When I run this line of codepython train_iti_gen.py --prompt='a headshot of a person' --attr-list='Male,Skin_tone,Age' --epochs=30 --save-ckpt-per-epochs=10

### ISSUE THREAD

**Issue by pcxdi** [humansensinglab/ITI-GEN#2]

**Comment by pcxdi** [comment]
Traceback (most recent call last):
  File "train_iti_gen.py", line 32, in <module>
    iti_gen = ITI_GEN(args)
  File "/home/onescure/ITI-GEN-main/ITI-GEN/iti_gen/model.py", line 40, in __init__
    self.init_dataloader()
  File "/home/onescure/ITI-GEN-main/ITI-GEN/iti_gen/model.py", line 88, in init_dataloader
    self.trainloader.append(DataLoader(
  File "/root/anaconda3/envs/iti_gen/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 283, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/root/anaconda3/envs/iti_gen/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 215, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0
There is no use trying to shuffle=False

**Comment by daniel-gallo** [comment]
If you look at [model.py, line 90](https://github.com/humansensinglab/ITI-GEN/blob/bd66e480f9bd17a5ce018189634e66ae5e7bc2db/iti_gen/model.py#L90), the batch size is defined as the length of the dataset divided by the number of steps per epoch. Is it possible that you didn't download the datasets to the `data/` folder? If that's the case, take a look at the [Data Preparation section of the README](https://github.com/humansensinglab/ITI-GEN/tree/main?tab=readme-ov-file#data-preparation).

**Comment by Xuanbai-Chen** [comment]
Thanks for your interest! I think @daniel-gallo is correct, you need to download the datasets first.

**Comment by pcxdi** [comment]
Thank you for your answer. I have successfully downloaded the fairface data set before and put it in the specified directory _data_/. Do I need to download all the data sets before training。Now I'm downloading the entire dataset

**Comment by Xuanbai-Chen** [comment]
Please download the first **three** datasets to train for human attributes. You only need to download LHQ if you want the generated images balanced across scene attributes.
