### ISSUE TITLE
The gap between FID indicators is too large

### ISSUE THREAD

**Issue by pcxdi** [humansensinglab/ITI-GEN#7]
Dear Author,
First of all, thank you for the great contribution made by your wonderful paper. When I tested the FID index of a single attribute male, the result showed that FID 337 had a huge gap with the FID score of a single attribute in the paper。The picture is as follows：

![Uploading a.png…]()

**Comment by Xuanbai-Chen** [comment]
Thank you for your interest in our work.

1. It seems the picture has not been uploaded successfully.
2. In terms of how the FID in paper is computed. Please refer to this [comment](https://github.com/humansensinglab/ITI-GEN/issues/1#issuecomment-2014411262).
